### ISSUE TITLE
Error when building 1.0.0-beta

### ISSUE THREAD

**Issue by dlqqq** [aws/sagemaker-distribution#97] opened 2023-10-19 19:04 UTC
I am seeing the following an error when building the images. The images are still being built and named, but an error is being printed afterwards. Here is how I am building the image:

```sh
# convenience for SageMaker Distribution
export SMD_DEFAULT_VERSION="1.0.0-beta"
export SMD_CONDA_ENV="sagemaker-distribution"
function smdi-build() {
    local version="${1:-$SMD_DEFAULT_VERSION}"
    echo "Entering $SMD_CONDA_ENV Conda environment..."
    conda activate $SMD_CONDA_ENV
    echo "Building SMD image v$version..."
    python ./src/main.py build \
        --target-patch-version $version \
        --force \
        --skip-tests
}
```

Here is the terminal output:

```
% smdi-build
Entering sagemaker-distribution Conda environment...
Building SMD image v1.0.0-beta...
Successfully built an image with id: sha256:5fd94f2711351c8a29909e6c09e02a80a2ea80360e4c34d84a8f2c32b112fbe2
[WARN]: Generating CHANGELOG is skipped because 'source-version.txt' isn't found.
Successfully built an image with id: sha256:1de8571f9d9c798c66972891e16546996a45023218eebd94711d593cc8fbb703
[WARN]: Generating CHANGELOG is skipped because 'source-version.txt' isn't found.
Traceback (most recent call last):
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda/models/version.py", line 43, in __call__
    return cls._cache_[arg]
           ~~~~~~~~~~~^^^^^
KeyError: '>=2.0.0,'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda/cli/common.py", line 95, in arg2spec
    spec = MatchSpec(arg)
           ^^^^^^^^^^^^^^
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda/models/match_spec.py", line 55, in __call__
    return super().__call__(**parsed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda/models/match_spec.py", line 179, in __init__
    self._match_components = self._build_components(**kwargs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda/models/match_spec.py", line 414, in _build_components
    return frozendict(_make_component(key, value) for key, value in kwargs.items())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda/_vendor/frozendict/__init__.py", line 21, in __init__
    self._dict = self.dict_cls(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda/models/match_spec.py", line 414, in <genexpr>
    return frozendict(_make_component(key, value) for key, value in kwargs.items())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda/models/match_spec.py", line 428, in _make_component
    matcher = _implementors[field_name](value)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda/models/version.py", line 45, in __call__
    val = cls._cache_[arg] = super().__call__(arg)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda/models/version.py", line 516, in __init__
    vspec_str, matcher, is_exact = self.get_matcher(vspec)
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda/models/version.py", line 521, in get_matcher
    vspec = treeify(vspec)
            ^^^^^^^^^^^^^^
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda/models/version.py", line 380, in treeify
    apply_ops("(")
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda/models/version.py", line 354, in apply_ops
    raise InvalidVersionSpec(spec_str, "cannot join single expression")
conda.exceptions.InvalidVersionSpec: Invalid version '>=2.0.0,': cannot join single expression

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/home/dlq/workplace/sagemaker-distribution/./src/main.py", line 384, in <module>
    parse_args(get_arg_parser())
  File "/local/home/dlq/workplace/sagemaker-distribution/./src/main.py", line 380, in parse_args
    args.func(args)
  File "/local/home/dlq/workplace/sagemaker-distribution/./src/main.py", line 140, in build_images
    generate_release_notes(target_version)
  File "/local/home/dlq/workplace/sagemaker-distribution/src/release_notes_generator.py", line 51, in generate_release_notes
    image_type_package_metadata = _get_image_type_package_metadata(target_version_dir)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/dlq/workplace/sagemaker-distribution/src/release_notes_generator.py", line 42, in _get_image_type_package_metadata
    image_type_package_metadata[image_generator_config['image_type']] = _get_installed_packages(
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/dlq/workplace/sagemaker-distribution/src/release_notes_generator.py", line 16, in _get_installed_packages
    required_packages_from_target = get_match_specs(
                                    ^^^^^^^^^^^^^^^^
  File "/local/home/dlq/workplace/sagemaker-distribution/src/utils.py", line 39, in get_match_specs
    assert len(requirement_spec.environment.dependencies) == 1
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda_env/specs/requirements.py", line 49, in environment
    return env.Environment(name=self.name, dependencies=dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda_env/env.py", line 237, in __init__
    self.dependencies = Dependencies(dependencies)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda_env/env.py", line 198, in __init__
    self.parse()
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda_env/env.py", line 210, in parse
    self["conda"].append(common.arg2spec(line))
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dlq/miniconda3/envs/sagemaker-distribution/lib/python3.11/site-packages/conda/cli/common.py", line 99, in arg2spec
    raise CondaValueError("invalid package specification: %s" % arg)
conda.exceptions.CondaValueError: invalid package specification: conda-forge::pytorch-gpu[version='>=2.0.0,']
```

**Comment by JasonWeill** [comment] 2023-10-19 19:08
Thanks for opening this! I'm also seeing this issue.

**Comment by dlqqq** [comment] 2023-10-19 19:30
Spoke with Clayton Parnell, another contributor to this repo. Apparently this is caused due to the trailing commas present in the package declarations in the `*.env.in` files. These appeared due to a bug fixed by https://github.com/aws/sagemaker-distribution/pull/55, but the issue persists as the trailing commas were not removed retroactively.

Since this appears to be a minor concern, we should wait until after the 1.0.0 release to fix this to avoid needing to backport a fix to 2 branches.

**Comment by claytonparnell** [comment] 2023-10-19 19:30
Related issue #51

**Comment by balajisankar15** [comment] 2023-10-19 20:12
@dlqqq 

This is a duplicate of the original issue(https://github.com/aws/sagemaker-distribution/issues/51) and it was actually fixed as part of https://github.com/aws/sagemaker-distribution/pull/55

There is no other fix needed for this bug (you reported). 

What changed now after the fix was released:
* We started auto-generating release notes. 

Looks like the release-notes script ran into the same issue (for 1.0.0-beta). 

This is because 1.0.0-beta was released before this fix was published. Can you update 1.0.0-beta env.in files in your PR to remove the commas?.

**Comment by balajisankar15** [comment] 2023-12-12 19:18
Treating this as stale.

**Closed by balajisankar15** 2023-12-12 19:18 UTC
